- alias: Flood Sensor
  trigger:
    platform: state
    entity_id: binary_sensor.fibaro_system_fgfs101_flood_sensor_flood
  action:
    service: notify.all_phones
    data:
      message: "Flood Sensor: {{ states.binary_sensor.fibaro_system_fgfs101_flood_sensor_flood.state }}"
      data:
        push:
          badge: 999

- alias: Front Door Open
  trigger:
    platform: state
    entity_id: sensor.front_door
  condition:
    condition: state
    entity_id: group.presence
    state: 'not_home'
  action:
    service: notify.all_phones
    data:
      message: "Front Door: {{ states.sensor.front_door.state }}"
      data:
        push:
          badge: 1


- alias: Back Door Open
  trigger:
    platform: state
    entity_id: sensor.back_door
  condition:
    condition: state
    entity_id: group.presence
    state: 'not_home'
  action:
    service: notify.all_phones
    data:
      message: "Back Door Sensor: {{ states.sensor.back_door.state }}"
      data:
        push:
          badge: 2

- alias: Hallway Motion
  trigger:
    platform: state
    entity_id: sensor.hall_motion
  condition:
    condition: state
    entity_id: group.presence
    state: 'not_home'
  action:
    service: notify.all_phones
    data:
      message: "Hallway Movement: {{ states.sensor.hall_motion.state }}"
      data:
        push:
          badge: 3


- alias: 'Christmas Lights Off'
  trigger:
    platform: time
    at: '00:30:00'
  action:
    service: switch.turn_off
    entity_id: switch.aeotec_zw096_smart_switch_6_switch_2
 
- alias: 'Christmas Lights On'
  trigger:
    platform: time
    at: '07:00:00'
  action:
    service: switch.turn_on
    entity_id: switch.aeotec_zw096_smart_switch_6_switch_2

- alias: PIR Arm
  trigger:
    platform: state
    entity_id: group.presence
  condition:
    condition: state
    entity_id: group.presence
    state: 'not_home'
  action:
    service: switch.turn_on
    entity_id: switch.hall_camera_motion_detection

- alias: PIR Disarm
  trigger:
    platform: state
    entity_id: group.presence
  condition:
    condition: state
    entity_id: group.presence
    state: 'home'
  action:
    service: switch.turn_off
    entity_id: switch.hall_camera_motion_detection

