homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 34
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  customize: !include customise.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: 
  ssl_certificate: /home/homeassistant/fullchain.pem
  ssl_key: /home/homeassistant/privkey.pem


# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor: !include sensors.yaml

notify: !include notify.yaml

# Text to speech
tts:
  platform: google

group: !include groups.yaml
automation: !include automations.yaml

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_key

camera:
  - platform: generic
    still_image_url: !secret blueiris_hall
    name: Hall
    username: !secret blueiris_user
    password: !secret blueiris_pass

switch:
  - platform: hikvisioncam
    host: !secret hall_camera_ip
    username: !secret hall_camera_user
    password: !secret hall_camera_pass
    name: Hall Camera Motion Detection

ios:

hue:
  bridges:
    - host: !secret hue_ip
