-  platform: yr


- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: processor_use
    - type: load_5m

- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'


- platform: template
  sensors:
    front_door:
      value_template: '{% if states.binary_sensor.fibaro_system_fgk10x_door_opening_sensor_sensor %}
        {% if states.binary_sensor.fibaro_system_fgk10x_door_opening_sensor_sensor.state == "on" %}
          Open
        {% else %}
          Closed
        {% endif %}
        {% else %}
        n/a
        {% endif %}'
      friendly_name: 'Front Door (binary)'

- platform: template
  sensors:
    front_door2:
      value_template: >-
          {%- if is_state('sensor.fibaro_system_fgk10x_door_opening_sensor_access_control', '22') -%}
            Open
          {%- elif is_state('sensor.fibaro_system_fgk10x_door_opening_sensor_access_control', '23') -%}
            Closed
          {%- else -%}
            Unknown
          {%- endif -%}
      friendly_name: 'Front Door'


- platform: template
  sensors:
    back_door:
      value_template: '{% if states.binary_sensor.aeotec_zw112_door_window_sensor_6_sensor %}
        {% if states.binary_sensor.aeotec_zw112_door_window_sensor_6_sensor.state == "on" %}
          Open
        {% else %}
          Closed
        {% endif %}
        {% else %}
        n/a
        {% endif %}'
      friendly_name: 'Back Door'

- platform: template
  sensors:
    hall_motion:
      value_template: >-
          {%- if is_state('sensor.aeotec_zw100_multisensor_6_burglar', '3') -%}
            Tamper
          {%- elif is_state('sensor.aeotec_zw100_multisensor_6_burglar', '8') -%}
            Motion
          {%- elif is_state('sensor.aeotec_zw100_multisensor_6_burglar', '0') -%}
            OK
          {%- elif is_state('sensor.aeotec_zw100_multisensor_6_burglar', '254') -%}
            OK
          {%- else -%}
            Unknown
          {%- endif -%}
      friendly_name: 'Hall Motion'

- platform: template
  sensors:
    batt_frontdoor:
      friendly_name: 'Front Door Battery'
      value_template: '{{ states.zwave.fibaro_system_fgk10x_door_opening_sensor.attributes.battery_level }}'
      unit_of_measurement: '%'
      entity_id: zwave.fibaro_system_fgk10x_door_opening_sensor

- platform: template
  sensors:
    batt_flood:
      friendly_name: 'Flood Sensor Battery'
      value_template: '{{ states.zwave.fibaro_system_fgfs101_flood_sensor.attributes.battery_level }}'
      unit_of_measurement: '%'
      entity_id: zwave.fibaro_system_fgfs101_flood_sensor

- platform: template
  sensors:
    batt_back_door:
      friendly_name: 'Back Door Battery'
      value_template: '{{ states.zwave.aeotec_zw112_door_window_sensor_6.attributes.battery_level }}'
      unit_of_measurement: '%'
      entity_id: zwave.aeotec_zw112_door_window_sensor_6

- platform: template
  sensors:
    batt_multisensor:
      friendly_name: 'Multisensor Battery'

      value_template: '{{ states.zwave.aeotec_zw100_multisensor_6.attributes.battery_level }}'
      unit_of_measurement: '%'
      entity_id: zwave.aeotec_zw100_multisensor_6

